### ISSUE TITLE
Multiple controlled trees with live data loosing registered tree affecting drag and drop sometimes.

### ISSUE THREAD

**Issue by CraigDeverall** [lukasbach/react-complex-tree#258]
**Bug Description**
When using multiple controlled trees that are driven by dynamic data and dragging and dropping on the first tree in dom. Sometimes the component can get into a state where the linearItems for the first tree are not present and this causes an error when dragging over items. 

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.eval [as current] (useOnDragOverTreeHandler.js:67:1)
    at Object.eval [as onDragOverTreeHandler] (use-stable-handler.js:11:1)
    at onDragOver (TreeManager.js:44:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)

In my case I am expecting a 'mainTree' (the first tree child) to also be present here:
![image](https://user-images.githubusercontent.com/3393968/234727372-5807015f-aa43-4068-a719-ec5694883cec.png)

I have tried and failed to checkout the repository and build react-complex-tree locally and link it to my project to debug unfortunately. I had wanted to investigate the setTimeout in UseControlledTreeEnvironmentProps.ts

![image](https://user-images.githubusercontent.com/3393968/234727947-4a09813f-75e7-4080-bd64-fc5174238be2.png)

**To Reproduce**

- Use a ControlledTreeEnvironment. 
- Using live data from the database, changes in the tree save the data to backend and update the treeData passed to ControlledTreeEnvironment
- I have 3 Tree components nested inside this ( all using different roots of the same data)
- It doesn't happen initially, but after a subsequent render (ie change one of the treeRoots of the 2nd or 3rd trees and re-render after a item clicked action from the mainTree)
- Drag and drop on the first child tree. Notice that it causes errors above.

**Expected behaviour**
That the mainTree linearItems would still be there and that this error wouldn't occur in this situation.

On MacbookPro using Chrome.

Unfortunately I can't share my exact code, I will try to spend some time reproduce this in a sandbox.

**Comment by CraigDeverall** [comment]
Another clue I noticed is that prior to this happening there is an 'undefined' tree unregistered. 
I could see this after logging like this:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/3393968/235026873-dbc3b7af-145b-40f9-850c-3878b6ca7cc2.png">

**Comment by lukasbach** [comment]
Hey, thanks for your report! Can you provide maybe an "anonymized" version of the code that creates the RCT instance, i.e. the react components for the tree and the tree environment? To me it looks like there are some inconsistencies in how the tree IDs are maintained by or provided to RCT.

**Comment by asurabhi** [comment]
@lukasbach Faced the same issue in my app.
Changes into attached file solved the issue for v2.6.0.
I created a sample app to reproduce the issue, but this issue is not happening with that.

This issue occurs when one of the trees in the environment is reloaded.

I think changes in attached patch are fine.
Is it possible to incorporate these changes in next release?

**Comment by asurabhi** [comment]
@lukasbach Attached the patch which solved the issue.

[rct-258.patch](https://github.com/user-attachments/files/28420395/rct-258.patch)

**Comment by asurabhi** [comment]
I can raise a PR if you make me a contributor

**Comment by lukasbach** [comment]
Hi @asurabhi, thanks for looking into this! I can add your patch to the repo, but if you want to be attributed as contributor, I would be happy to merge a PR by yours. I think you should be able to just open a PR by forking the repo and pushing the changes there.

**Comment by as666499** [comment]
@lukasbach Can you merge the PR #439

**Comment by lukasbach** [comment]
Hi @as666499, sorry for the delay. I've merged your PR and released the changes, thanks for your contribution!
